// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezijjwmswjoxhyubnrrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6aWpqd21zd2pveGh5dWJucnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTc4NDIsImV4cCI6MjA3MDE5Mzg0Mn0.h_-fcdodAGauKFZYluqfqYIo0GyAQstSy3WOWCO67_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});